### ISSUE TITLE
AttributeError: 'HTTPError' object has no attribute 'Code'

### ISSUE THREAD

**Issue by lukaszun** [Microsoft/wopi-validator-cli-python#6]
Im still getting this error while launching: WopiValidatorExecutor. Log says:

09/16/2016 02:07:46 PM : INFO : WOPI Discovery Service Url: https://onenote.officeapps-df.live.com/hosting/discovery
09/16/2016 02:07:46 PM : INFO : Starting new HTTPS connection (1): onenote.officeapps-df.live.com
09/16/2016 02:07:47 PM : DEBUG : "GET /hosting/discovery HTTP/1.1" 200 4223
09/16/2016 02:07:47 PM : INFO : WopiValidator TestEndpoint Url: https://onenote.officeapps-df.live.com/hosting/GetWopiTestInfo.ashx
09/16/2016 02:07:47 PM : INFO : Starting new HTTPS connection (1): onenote.officeapps-df.live.com
09/16/2016 02:07:47 PM : DEBUG : "GET /hosting/GetWopiTestInfo.ashx?testcategory=All&WOPISrc=http%3A%2F%2Flocalhost%3A9000%2Fwopi%2Ffiles%2F12&access_token=eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50SWQiOjEsImZpbGVEb2N1bWVudElkIjoxNiwidG9rZW5UeXBlIjoiV09QSSIsImV4cCI6MTQ3NDAyOTc0MH0.5T82-SWD6aU8rfGCuva6waE11XSi13kvkLmvENr2L3U&access_token_ttl=0 HTTP/1.1" 404 1245

**Comment by fabiovazquez** [comment]
Hi,

Based on our logs, the WOPISrc parameter seesm to be pointing to "localhost". You should use a valid internet domain that exists as part on Microsoft's WOPI allow list.

HTH!
Fabio

**Comment by lukaszun** [comment]
Hi Fabio, 
I've changed localhost to my domain and still getting same error so I think that's not the root problem. I tried using direct url to test application: https://onenote.officeapps-df.live.com/hosting/GetWopiTestInfo.ashx?testcategory=All&WOPISrc=http://wopi-dev.volanto.pl:10055/wopi/files/12 and still getting 404 as answer.

**Comment by fabiovazquez** [comment]
Hi, 
I couldn't find the domain you are using for your WOPI endpoint (volanto.pl) on our internal allow list. Are you already a member of the Office 365 Cloud Storage Partner Program, as described on the link below?

http://wopi.readthedocs.io/en/latest/#using-the-wopi-protocol-to-integrate-with-office-online

Thanks!
Fabio

**Comment by tylerbutler** [comment]
Since @fabiovazquez answered this question already, and the root problem is that the domain is not on the allow list, I am closing this issue.
