### ISSUE TITLE
AttributeError: 'HTTPError' object has no attribute 'Code'

### ISSUE THREAD

**Issue by suhasg** [Microsoft/wopi-validator-cli-python#9]
Our domain (test-wopi.sycamoreinformatics.com) is whitelisted under Office 365 Cloud Storage Partner Program.
But when I ran 

`WopiValidatorExecutor "https://onenote.officeapps-df.live.com/hosting/WopiTestFrame.aspx?ui=1033&rs=1033&dchat=false&IsLicensedUser=0&testcategory=OfficeOnline&WOPISrc=https://sgdevwopi.test-wopi.sycamoreinformatics.com/wopi/files/32" "xxxxxxxxxxx-access--token--"`

I get this error:

<img width="1200" alt="screen shot 2018-04-12 at 1 41 46 pm" src="https://user-images.githubusercontent.com/720202/38664476-56f87d40-3e57-11e8-99fd-d3953be813c4.png">

When tried to post the word view url in iframe i get a loading icon with `Word Online`. Thats all. Nothing else.

How should we proceed further?

**Comment by tylerbutler** [comment]
The discovery URL is incorrect: https://github.com/microsoft/wopi-validator-cli-python/blob/8ca60d7e921fdf4000d2d5b06b1ca86e195cacdd/WopiValidatorExecutor/ExecutorConfig.ini#L6

It should be updated to have the correct discovery URLs per <https://wopi.readthedocs.io/en/latest/build_test_ship/environments.html#wopi-discovery-urls>

**Comment by suhasg** [comment]
Resolved
